# Generated by Django 4.2.6 on 2023-11-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('elo', models.DecimalField(decimal_places=1, default=500.0, max_digits=6)),
            ],
        ),
    ]
