# Generated by Django 5.2.11 on 2026-02-04 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stage_type', models.CharField(choices=[('sw', 'Swiss'), ('se', 'Single Elimination'), ('rr', 'Round Robin')], max_length=2)),
                ('round_count', models.IntegerField(blank=True, default=0, null=True)),
                ('advance_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('k_factor', models.IntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_a', models.IntegerField()),
                ('score_b', models.IntegerField()),
                ('best_of', models.IntegerField(choices=[(1, 'BO1'), (3, 'BO3'), (5, 'BO5')], default=3)),
                ('game_wins_a', models.IntegerField(default=0)),
                ('game_wins_b', models.IntegerField(default=0)),
                ('round', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_a', to='Elo.player')),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_b', to='Elo.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_winner', to='Elo.player')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elo.stage')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Elo.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='MatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_a_before', models.DecimalField(decimal_places=1, max_digits=6)),
                ('elo_b_before', models.DecimalField(decimal_places=1, max_digits=6)),
                ('score_a', models.DecimalField(decimal_places=2, max_digits=3)),
                ('best_of', models.IntegerField()),
                ('stage_type', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elo.match')),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_player_a', to='Elo.player')),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_player_b', to='Elo.player')),
            ],
        ),
        migrations.AddField(
            model_name='stage',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elo.tournament'),
        ),
    ]
