# Generated by Django 5.2.11 on 2026-02-04 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elo', '0002_stage_tournament_player_point_match_matchlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Elo.tournament'),
        ),
    ]
