# Generated by Django 5.2.11 on 2026-02-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elo', '0003_alter_stage_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='score_a',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score_b',
        ),
    ]
